# Generated by Django 5.2.4 on 2025-07-12 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='receiver_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_swaps', to='swap.skill'),
        ),
        migrations.AddField(
            model_name='swap',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='requester_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_swaps', to='swap.skill'),
        ),
        migrations.AddField(
            model_name='rating',
            name='swap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='swap.swap'),
        ),
    ]
