# Generated by Django 5.2.4 on 2025-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='proposed_time',
        ),
        migrations.AddField(
            model_name='swap',
            name='proposed_time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
